export const dummyData = [
    {
        _id: 'can1',
        offset: '0px',
        name: 'Street Beer',
        tagline: 'Feel the vibe',
        description1:
            'Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Porttitor eget dolor morbi non. Augue ut lectus arcu bibendum at varius vel.',
        description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, eum.',
        isNew: false,
        alcohol: '4.6',
        size: 330,
        cost: 4.99,
        primaryColor: '#f0690a',
        secondaryColor: '#23148f',
    },
    {
        _id: 'can2',
        offset: '0px',
        name: 'Street Beer',
        tagline: 'Feel the vibe',
        description1:
            'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam accusamus fugit sint necessitatibus quos atque quis soluta assumenda omnis consequuntur.',
        description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, eum.',
        isNew: false,
        alcohol: '4.8',
        size: 330,
        cost: 4.99,
        primaryColor: '#fb7edf',
        secondaryColor: '#23148f',
    },
    {
        _id: 'can3',
        offset: '0px',
        name: 'Street Beer',
        tagline: 'Feel the vibe',
        description1:
            'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam accusamus fugit sint necessitatibus quos atque quis soluta assumenda omnis consequuntur.',
        description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, eum.',
        isNew: false,
        alcohol: '5.1',
        size: 330,
        cost: 4.99,
        primaryColor: '#98cb23',
        secondaryColor: '#fff',
    },
    {
        _id: 'can4',
        offset: '0px',
        name: 'Half Cocked',
        tagline: 'Keep it simple',
        description1:
            'Blandit libero volutpat sed cras ornare arcu. Ac auctor augue mauris augue neque gravida in fermentum et. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum.',
        description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, eum.',
        isNew: false,
        alcohol: '5.1',
        size: 330,
        cost: 5.99,
        primaryColor: '#BD2c02',
        secondaryColor: '#fff',
    },
    // {
    //     _id: 'can5',
    //     offset: '-290px',
    //     name: 'Chebougan Brewing',
    //     tagline: 'Blood Orange Honey',
    //     description1:
    //         'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam accusamus fugit sint necessitatibus quos atque quis soluta assumenda omnis consequuntur.',
    //     description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, eum.',
    //     isNew: false,
    //     alcohol: '5.1',
    //     size: 330,
    //     cost: 5.99,
    //     primaryColor: '#f0881f',
    //     secondaryColor: '#3e1e20',
    // },
    // {
    //     _id: 'can6',
    //     offset: '-290px',
    //     name: 'Heady Hunter',
    //     tagline: 'Hazy India Pale Ale',
    //     description1:
    //         'Auctor eu augue ut lectus. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Donec massa sapien faucibus et molestie ac feugiat sed lectus. Enim eu turpis egestas pretium.',
    //     description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, eum.',
    //     isNew: false,
    //     alcohol: '6.1',
    //     size: 360,
    //     cost: 5.99,
    //     primaryColor: '#f0690a',
    //     secondaryColor: '#020202',
    // },
    // {
    //     _id: 'can7',
    //     offset: '0px',
    //     name: 'Blackwoods Pale Ale',
    //     tagline: 'Sunday Road',
    //     description1:
    //         'Odio facilisis mauris sit amet massa vitae tortor. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum. Purus in massa tempor nec feugiat nisl pretium.',
    //     description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, eum.',
    //     isNew: false,
    //     alcohol: '6.1',
    //     size: 360,
    //     cost: 3.99,
    //     primaryColor: '#5eaaa8',
    //     secondaryColor: '#fff',
    // },
    // {
    //     _id: 'can8',
    //     offset: '0px',
    //     name: 'Enigma Pale Ale',
    //     tagline: 'Sunday Road',
    //     description1:
    //         'Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Habitant morbi tristique senectus et netus. Parturient montes nascetur ridiculus mus mauris vitae ultricies. Ultrices sagittis orci a scelerisque purus semper eget. Interdum posuere lorem ipsum dolor.',
    //     description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, eum.',
    //     isNew: false,
    //     alcohol: '6.1',
    //     size: 360,
    //     cost: 3.99,
    //     primaryColor: '#f0690a',
    //     secondaryColor: '#fff',
    // },
]
